#!/usr/bin/env python3
"""
apply_42_ipc_patch.py

Applies the multi-threaded IPC patch to a fresh clone of nasa-itc/42 (nos3-main).
Called by prepare.sh after git clone and before make.

Usage:
    python3 apply_42_ipc_patch.py <path_to_42> <path_to_patch_dir>
"""

import os
import sys
import shutil
import re


def patch_txrx_ipc(txrx_path):
    """Apply surgical edits to Source/AutoCode/TxRxIPC.c (autogenerated file)."""
    if not os.path.isfile(txrx_path):
        print(f"  WARNING: {txrx_path} not found, skipping TxRxIPC patch.")
        return

    with open(txrx_path, "r") as f:
        content = f.read()

    # Guard: don't double-patch
    if "if (Socket <= 0) return;" in content:
        print(f"  TxRxIPC.c already patched, skipping.")
        return

    # 1. Add socket guard before write() in WriteToSocket
    content = content.replace(
        "Success = write(Socket,Msg,MsgLen);",
        "if (Socket <= 0) return;\n      Success = write(Socket,Msg,MsgLen);",
        1,  # only first occurrence (WriteToSocket)
    )

    # 2. Replace exit(1) after write error with return
    content = content.replace(
        'printf("Error writing to socket in WriteToSocket.\\n");\n         exit(1);',
        'printf("WriteToSocket: Client disconnected (write error).\\n");\n         return;',
    )

    # 3. Add socket guard before read() in ReadFromSocket
    content = content.replace(
        "NumBytes = read(Socket,Msg,16384);",
        "if (Socket <= 0) return;\n      NumBytes = read(Socket,Msg,16384);",
        1,  # only first occurrence
    )

    # 4. Change "NumBytes < 0" to "NumBytes <= 0" to catch clean disconnect
    content = content.replace(
        "if (NumBytes < 0)",
        "if (NumBytes <= 0)",
    )

    with open(txrx_path, "w") as f:
        f.write(content)

    print(f"  Patched: Source/AutoCode/TxRxIPC.c (graceful disconnect handling)")


def apply_patch(forty_two_dir, patch_dir):
    """Copy patched source files and apply in-place edits."""

    if not os.path.isfile(os.path.join(forty_two_dir, "Source", "42ipc.c")):
        print(f"ERROR: {forty_two_dir} does not appear to be a 42 source directory.")
        sys.exit(1)

    if not os.path.isdir(patch_dir):
        print(f"ERROR: Patch directory {patch_dir} not found.")
        sys.exit(1)

    print(f"Applying multi-threaded IPC patch to: {forty_two_dir}")

    # Copy overlay files (42ipc.c)
    files_copied = 0
    for root, dirs, files in os.walk(patch_dir):
        for filename in files:
            if filename.endswith(".md"):
                continue  # skip README
            src_path = os.path.join(root, filename)
            rel_path = os.path.relpath(src_path, patch_dir)
            dst_path = os.path.join(forty_two_dir, rel_path)

            dst_dir = os.path.dirname(dst_path)
            os.makedirs(dst_dir, exist_ok=True)

            shutil.copy2(src_path, dst_path)
            print(f"  Patched: {rel_path}")
            files_copied += 1

    # Apply surgical patches to TxRxIPC.c
    txrx_path = os.path.join(forty_two_dir, "Source", "AutoCode", "TxRxIPC.c")
    patch_txrx_ipc(txrx_path)

    print(f"")
    print(f"Patch applied ({files_copied} file(s) replaced, TxRxIPC.c edited in-place).")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <path_to_42> <path_to_patch_dir>")
        sys.exit(1)

    apply_patch(sys.argv[1], sys.argv[2])
