"""initial

Revision ID: fe7953b6226e
Revises: 
Create Date: 2024-08-05 11:25:09.349956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7953b6226e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endian', sa.String(length=100), nullable=False),
    sa.Column('stream_id', sa.String(length=100), nullable=True),
    sa.Column('function_code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('default', sa.String(length=256), nullable=False),
    sa.Column('min', sa.String(length=256), nullable=True),
    sa.Column('max', sa.String(length=256), nullable=True),
    sa.Column('states', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('offset', sa.String(length=256), nullable=False),
    sa.Column('endian', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercepted_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_command_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_command_id'], ['command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercepted_command_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_parameter_id', sa.Integer(), nullable=False),
    sa.Column('intercepted_command_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['base_parameter_id'], ['command_parameter.id'], ),
    sa.ForeignKeyConstraint(['intercepted_command_id'], ['intercepted_command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intercepted_command_parameter')
    op.drop_table('intercepted_command')
    op.drop_table('command_parameter')
    op.drop_table('command')
    op.drop_table('target')
    op.drop_table('setting')
    # ### end Alembic commands ###
